# Notebook 1: Data Loading & Cleaning
Stages 1-5

In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer, KNNImputer

Upload your dataset in Colab.

In [6]:
#from google.colab import files
#uploaded=files.upload()

In [5]:
df=pd.read_excel("customer_data_raw.xlsx")
df.head()

,CustomerID,Age,Gender,MaritalStatus,Education,ExperienceYears,Salary,Bonus,SalaryText,JoinDate,...,RandomText,BooleanText,Region,ProductCategory,NumOrders,ReturnRate,ChurnRiskScore,FakeID,AllMissing,Correlation2
0,CUST1000,31.0,M,Married,NaN,21,45494.0,20444,45494,11/02/2019,...,Lorem,False,South,Electronics,72,0.15,57.11,ID-95478,NaN,45494.0
1,CUST1001,52.0,female,single,NaN,31,145380.0,9076,145380,2021-01-04,...,Lorem,False,East,Electronics,96,0.78,28.84,ID-66127,NaN,145380.0
2,CUST1002,59.0,male,single,High School,23,110012.0,12876,110012,2024-03-15,...,Ipsum,True,South,Electronics,39,0.25,33.19,ID-91266,NaN,110012.0
3,CUST1003,55.0,F,Divorced,Master,24,150732.0,24361,150732,2024-04-17,...,NaN,False,South,Fashion,51,0.68,16.95,ID-51244,NaN,150732.0
4,CUST1004,59.0,male,single,Bachelor,18,126350.0,26396,126350,2019-07-21,...,Test,False,North,Books,23,0.13,96.35,ID-76953,NaN,126350.0

In [7]:
df.tail()

,CustomerID,Age,Gender,MaritalStatus,Education,ExperienceYears,Salary,Bonus,SalaryText,JoinDate,...,RandomText,BooleanText,Region,ProductCategory,NumOrders,ReturnRate,ChurnRiskScore,FakeID,AllMissing,Correlation2
495,CUST1010,22.0,F,single,Bachelor,36,142997.0,1743,142997,2020-10-29,...,NaN,True,South,Grocery,6,0.55,84.25,ID-55697,NaN,142997.0
496,CUST1011,65.0,NaN,Divorced,High School,13,80887.0,12824,80887,2020-04-16,...,Test,True,East,Fashion,47,0.28,93.14,ID-33021,NaN,80887.0
497,CUST1012,65.0,M,NaN,Master,21,198333.0,4030,198333,2020-05-17,...,Test,True,North,Books,78,0.33,26.03,ID-23131,NaN,198333.0
498,CUST1013,26.0,Male,Divorced,NaN,39,158300.0,6929,158300,2023-11-10,...,Test,True,North,Electronics,10,0.45,10.22,ID-93877,NaN,158300.0
499,CUST1014,29.0,male,single,Master,2,124652.0,28921,124652,2023-12-23,...,Ipsum,True,South,Fashion,44,0.12,17.51,ID-48351,NaN,124652.0

In [8]:
df.shape

(500, 49)

In [9]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'MaritalStatus', 'Education',
       'ExperienceYears', 'Salary', 'Bonus', 'SalaryText', 'JoinDate',
       'LastPurchaseDate', 'City', 'Country', 'Department', 'JobLevel',
       'Remote', 'CreditScore', 'MonthlySpend', 'BMI', 'HeightCm', 'WeightKg',
       'Purchased', 'Target', 'Review', 'EmailVerified', 'LoyaltyTier',
       'ZipCode', 'Noise1', 'Noise2', 'ConstantCol', 'Salary_Copy', 'Age_Copy',
       'SkewedIncome', 'OutlierFeature', 'HighCardCategory', 'InvalidDate',
       'LeakageFeature', 'MostlyMissing', 'DuplicateGroup', 'RandomText',
       'BooleanText', 'Region', 'ProductCategory', 'NumOrders', 'ReturnRate',
       'ChurnRiskScore', 'FakeID', 'AllMissing', 'Correlation2'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 49 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        500 non-null    str
 1   Age               477 non-null    float64
 2   Gender            425 non-null    str
 3   MaritalStatus     388 non-null    str
 4   Education         390 non-null    str
 5   ExperienceYears   500 non-null    int64
 6   Salary            483 non-null    float64
 7   Bonus             500 non-null    int64
 8   SalaryText        483 non-null    object
 9   JoinDate          500 non-null    str
 10  LastPurchaseDate  500 non-null    str
 11  City              500 non-null    str
 12  Country           500 non-null    str
 13  Department        500 non-null    str
 14  JobLevel          500 non-null    str
 15  Remote            500 non-null    object
 16  CreditScore       500 non-null    int64
 17  MonthlySpend      500 non-null    float64
 18  BMI               500 non-null    float64
 19  HeightCm          500 non-null    int64
 20  WeightKg          500 non-null    int64
 21  Purchased         500 non-null    str
 22  Target            500 non-null    int64
 23  Review            404 non-null    str
 24  EmailVerified     349 non-null    float64
 25  LoyaltyTier       500 non-null    str
 26  ZipCode           337 non-null    float64
 27  Noise1            500 non-null    float64
 28  Noise2            500 non-null    int64
 29  ConstantCol       500 non-null    str
 30  Salary_Copy       483 non-null    float64
 31  Age_Copy          477 non-null    float64
 32  SkewedIncome      500 non-null    float64
 33  OutlierFeature    500 non-null    int64
 34  HighCardCategory  500 non-null    str
 35  InvalidDate       17 non-null     str
 36  LeakageFeature    500 non-null    int64
 37  MostlyMissing     100 non-null    float64
 38  DuplicateGroup    500 non-null    str
 39  RandomText        358 non-null    str
 40  BooleanText       500 non-null    bool
 41  Region            500 non-null    str
 42  ProductCategory   500 non-null    str
 43  NumOrders         500 non-null    int64
 44  ReturnRate        500 non-null    float64
 45  ChurnRiskScore    500 non-null    float64
 46  FakeID            500 non-null    str
 47  AllMissing        0 non-null      float64
 48  Correlation2      483 non-null    float64
dtypes: bool(1), float64(15), int64(10), object(2), str(21)
memory usage: 188.1+ KB

In [22]:
df.describe()

,Age,ExperienceYears,Salary,Bonus,CreditScore,MonthlySpend,BMI,HeightCm,WeightKg,Target,...,Age_Copy,SkewedIncome,OutlierFeature,LeakageFeature,MostlyMissing,NumOrders,ReturnRate,ChurnRiskScore,AllMissing,Correlation2
count,463.000000,485.000000,468.000000,485.000000,485.000000,485.000000,485.000000,485.000000,485.000000,485.000000,...,463.000000,485.000000,485.000000,485.000000,96.000000,485.000000,485.000000,485.000000,0.0,468.000000
mean,42.017279,19.698969,111126.767094,15468.484536,587.812371,24703.853753,26.680165,170.453608,76.507216,0.519588,...,42.017279,207007.059856,170.395876,0.519588,51.583333,49.185567,0.506062,51.929567,NaN,111126.767094
std,14.901979,11.732561,49193.076055,8264.660250,169.055824,14209.009760,7.574602,11.693769,19.045901,0.500132,...,14.901979,272772.745750,905.370761,0.500132,29.389818,29.003252,0.296618,28.604983,NaN,49193.076055
min,-10.000000,0.000000,25085.000000,1005.000000,301.000000,589.850000,12.470000,150.000000,45.000000,0.000000,...,-10.000000,0.000000,10.000000,0.000000,1.000000,0.000000,0.000000,0.310000,NaN,25085.000000
25%,30.000000,10.000000,67321.750000,8521.000000,446.000000,12717.080000,20.660000,160.000000,60.000000,0.000000,...,30.000000,6654.110000,33.000000,0.000000,24.750000,25.000000,0.250000,27.910000,NaN,67321.750000
50%,42.000000,20.000000,112128.000000,15322.000000,579.000000,24630.460000,25.880000,171.000000,77.000000,1.000000,...,42.000000,63495.980000,57.000000,1.000000,48.500000,48.000000,0.520000,49.850000,NaN,112128.000000
75%,55.000000,30.000000,151832.750000,22584.000000,736.000000,36875.440000,32.410000,180.000000,93.000000,1.000000,...,55.000000,328354.590000,81.000000,1.000000,77.500000,73.000000,0.770000,77.970000,NaN,151832.750000
max,65.000000,40.000000,199693.000000,29978.000000,899.000000,49829.330000,48.440000,190.000000,110.000000,1.000000,...,65.000000,995233.340000,9800.000000,1.000000,100.000000,100.000000,1.000000,99.890000,NaN,199693.000000

In [23]:
df.describe(include='all')

,CustomerID,Age,Gender,MaritalStatus,Education,ExperienceYears,Salary,Bonus,SalaryText,JoinDate,...,RandomText,BooleanText,Region,ProductCategory,NumOrders,ReturnRate,ChurnRiskScore,FakeID,AllMissing,Correlation2
count,485,463.000000,411,374,380,485.000000,468.000000,485.000000,468.0,485,...,346,485,485,485,485.000000,485.000000,485.000000,485,0.0,468.000000
unique,485,NaN,6,4,4,NaN,NaN,NaN,465.0,440,...,3,2,4,4,NaN,NaN,NaN,485,NaN,NaN
top,CUST1000,NaN,female,Divorced,PhD,NaN,NaN,NaN,198333.0,2024-06-30,...,Lorem,True,East,Electronics,NaN,NaN,NaN,ID-95478,NaN,NaN
freq,1,NaN,73,105,103,NaN,NaN,NaN,2.0,3,...,124,248,135,139,NaN,NaN,NaN,1,NaN,NaN
mean,NaN,42.017279,NaN,NaN,NaN,19.698969,111126.767094,15468.484536,NaN,NaN,...,NaN,NaN,NaN,NaN,49.185567,0.506062,51.929567,NaN,NaN,111126.767094
std,NaN,14.901979,NaN,NaN,NaN,11.732561,49193.076055,8264.660250,NaN,NaN,...,NaN,NaN,NaN,NaN,29.003252,0.296618,28.604983,NaN,NaN,49193.076055
min,NaN,-10.000000,NaN,NaN,NaN,0.000000,25085.000000,1005.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.310000,NaN,NaN,25085.000000
25%,NaN,30.000000,NaN,NaN,NaN,10.000000,67321.750000,8521.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,25.000000,0.250000,27.910000,NaN,NaN,67321.750000
50%,NaN,42.000000,NaN,NaN,NaN,20.000000,112128.000000,15322.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,48.000000,0.520000,49.850000,NaN,NaN,112128.000000
75%,NaN,55.000000,NaN,NaN,NaN,30.000000,151832.750000,22584.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,73.000000,0.770000,77.970000,NaN,NaN,151832.750000
max,NaN,65.000000,NaN,NaN,NaN,40.000000,199693.000000,29978.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,100.000000,1.000000,99.890000,NaN,NaN,199693.000000

In [12]:
df.dtypes

CustomerID              str
Age                 float64
Gender                  str
MaritalStatus           str
Education               str
ExperienceYears       int64
Salary              float64
Bonus                 int64
SalaryText           object
JoinDate                str
LastPurchaseDate        str
City                    str
Country                 str
Department              str
JobLevel                str
Remote               object
CreditScore           int64
MonthlySpend        float64
BMI                 float64
HeightCm              int64
WeightKg              int64
Purchased               str
Target                int64
Review                  str
EmailVerified       float64
LoyaltyTier             str
ZipCode             float64
Noise1              float64
Noise2                int64
ConstantCol             str
Salary_Copy         float64
Age_Copy            float64
SkewedIncome        float64
OutlierFeature        int64
HighCardCategory        str
InvalidDate             str
LeakageFeature        int64
MostlyMissing       float64
DuplicateGroup          str
RandomText              str
BooleanText            bool
Region                  str
ProductCategory         str
NumOrders             int64
ReturnRate          float64
ChurnRiskScore      float64
FakeID                  str
AllMissing          float64
Correlation2        float64
dtype: object

In [13]:
df.isnull().sum().sort_values(ascending=False)

AllMissing          500
InvalidDate         483
MostlyMissing       400
ZipCode             163
EmailVerified       151
RandomText          142
MaritalStatus       112
Education           110
Review               96
Gender               75
Age_Copy             23
Age                  23
Salary               17
SalaryText           17
Salary_Copy          17
Correlation2         17
CustomerID            0
CreditScore           0
Remote                0
JobLevel              0
Department            0
Country               0
City                  0
LastPurchaseDate      0
JoinDate              0
Bonus                 0
ExperienceYears       0
HeightCm              0
Target                0
Purchased             0
WeightKg              0
MonthlySpend          0
BMI                   0
SkewedIncome          0
ConstantCol           0
Noise1                0
Noise2                0
LoyaltyTier           0
HighCardCategory      0
LeakageFeature        0
OutlierFeature        0
BooleanText           0
DuplicateGroup        0
Region                0
ProductCategory       0
ReturnRate            0
NumOrders             0
FakeID                0
ChurnRiskScore        0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(15)

In [15]:
df=df.drop_duplicates()
df.shape

(485, 49)

In [16]:
num_cols=df.select_dtypes(include='number').columns
cat_cols=df.select_dtypes(exclude='number').columns
num_cols,cat_cols

(Index(['Age', 'ExperienceYears', 'Salary', 'Bonus', 'CreditScore',
        'MonthlySpend', 'BMI', 'HeightCm', 'WeightKg', 'Target',
        'EmailVerified', 'ZipCode', 'Noise1', 'Noise2', 'Salary_Copy',
        'Age_Copy', 'SkewedIncome', 'OutlierFeature', 'LeakageFeature',
        'MostlyMissing', 'NumOrders', 'ReturnRate', 'ChurnRiskScore',
        'AllMissing', 'Correlation2'],
       dtype='str'),
 Index(['CustomerID', 'Gender', 'MaritalStatus', 'Education', 'SalaryText',
        'JoinDate', 'LastPurchaseDate', 'City', 'Country', 'Department',
        'JobLevel', 'Remote', 'Purchased', 'Review', 'LoyaltyTier',
        'ConstantCol', 'HighCardCategory', 'InvalidDate', 'DuplicateGroup',
        'RandomText', 'BooleanText', 'Region', 'ProductCategory', 'FakeID'],
       dtype='str'))

In [19]:
# Remove columns that are 100% missing
num_df = df[num_cols].dropna(axis=1, how='all')

imp = SimpleImputer(strategy='median')

num_df = pd.DataFrame(
    imp.fit_transform(num_df),
    columns=num_df.columns
)

num_df.head()

,Age,ExperienceYears,Salary,Bonus,CreditScore,MonthlySpend,BMI,HeightCm,WeightKg,Target,...,Salary_Copy,Age_Copy,SkewedIncome,OutlierFeature,LeakageFeature,MostlyMissing,NumOrders,ReturnRate,ChurnRiskScore,Correlation2
0,31.0,21.0,45494.0,20444.0,760.0,21385.71,22.78,179.0,73.0,1.0,...,45494.0,31.0,196363.55,17.0,1.0,48.5,72.0,0.15,57.11,45494.0
1,52.0,31.0,145380.0,9076.0,890.0,23023.98,34.54,171.0,101.0,1.0,...,145380.0,52.0,296649.38,59.0,1.0,48.5,96.0,0.78,28.84,145380.0
2,59.0,23.0,110012.0,12876.0,590.0,6914.37,29.71,161.0,77.0,1.0,...,110012.0,59.0,6624.95,96.0,1.0,48.5,39.0,0.25,33.19,110012.0
3,55.0,24.0,150732.0,24361.0,416.0,37543.37,32.72,180.0,106.0,1.0,...,150732.0,55.0,158084.06,85.0,1.0,48.5,51.0,0.68,16.95,150732.0
4,59.0,18.0,126350.0,26396.0,877.0,32701.79,32.65,175.0,100.0,1.0,...,126350.0,59.0,146697.02,35.0,1.0,48.5,23.0,0.13,96.35,126350.0

In [21]:
print(df.shape)

print(len(num_cols))

print(df.select_dtypes(include='number').shape)

print(num_cols.tolist())

print(df.select_dtypes(include='number').columns.tolist())

(485, 49)
25
(485, 25)
['Age', 'ExperienceYears', 'Salary', 'Bonus', 'CreditScore', 'MonthlySpend', 'BMI', 'HeightCm', 'WeightKg', 'Target', 'EmailVerified', 'ZipCode', 'Noise1', 'Noise2', 'Salary_Copy', 'Age_Copy', 'SkewedIncome', 'OutlierFeature', 'LeakageFeature', 'MostlyMissing', 'NumOrders', 'ReturnRate', 'ChurnRiskScore', 'AllMissing', 'Correlation2']
['Age', 'ExperienceYears', 'Salary', 'Bonus', 'CreditScore', 'MonthlySpend', 'BMI', 'HeightCm', 'WeightKg', 'Target', 'EmailVerified', 'ZipCode', 'Noise1', 'Noise2', 'Salary_Copy', 'Age_Copy', 'SkewedIncome', 'OutlierFeature', 'LeakageFeature', 'MostlyMissing', 'NumOrders', 'ReturnRate', 'ChurnRiskScore', 'AllMissing', 'Correlation2']

In [20]:
imp=SimpleImputer(strategy='median')
num_df=pd.DataFrame(imp.fit_transform(df[num_cols]),columns=num_cols)
num_df.head()

c:\Users\HP\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: ['AllMissing']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

ValueError: Shape of passed values is (485, 24), indices imply (485, 25)

In [18]:
knn=KNNImputer(n_neighbors=5)
knn_df=pd.DataFrame(knn.fit_transform(df[num_cols]),columns=num_cols)
knn_df.head()

ValueError: Shape of passed values is (485, 24), indices imply (485, 25)

## Exercises
1. Find the column with most missing values.
2. How many duplicates were removed?
3. Compare median vs KNN imputation.